version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/project
    overwrite: true
    permission:
      - object: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        type:
          - directory
          - file
hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies.sh
#       timeout: 180
#       runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
#   ValidateService:
#     - location: scripts/validate_server.sh
#       timeout: 180
#       runas: ubuntu